// Generated by CoffeeScript 1.10.0
(function() {
  var express, models, router;

  express = require('express');

  router = express.Router();

  models = require('../models');

  router.get('/tasks', function(req, res, next) {
    return models.Task.findAll({
      order: 'createdAt DESC',
      limit: req.query.limit,
      offset: req.query.offset
    }).then(function(tasks) {
      return res.json(tasks || []);
    });
  });

  router.get('/tasks/:id', function(req, res, next) {
    return models.Task.findById(req.params.id).then(function(task) {
      return res.json(task || {});
    })["catch"](function(err) {
      res.status = 404;
      return res.json({
        msg: 'task does not exist'
      });
    });
  });

  router.post('/tasks', function(req, res, next) {
    return models.Task.create(req.body).then(function(created_obj) {
      return res.json(created_obj);
    })["catch"](function(err) {
      res.status = 400;
      return res.json({
        msg: err
      });
    });
  });

  router["delete"]('/tasks/:id', function(req, res, next) {
    return models.Task.destroy({
      where: {
        id: req.params.id
      }
    }).then(function(deleted_obj) {
      return res.json({
        id: req.params.id
      });
    });
  });

  router.put('/tasks/:id', function(req, res, next) {
    return models.Task.findById(req.params.id).then(function(task) {
      task.done = true;
      return task.save().then(function() {
        return res.json(task);
      })["catch"](function(err) {
        res.status = 400;
        return res.json({
          msg: 'can not complete task'
        });
      });
    })["catch"](function(err) {
      res.status = 404;
      return res.json({
        msg: 'task does not exist'
      });
    });
  });

  module.exports = router;

}).call(this);
