// Generated by CoffeeScript 1.10.0
(function() {
  var DEFULAT_LIMIT, DEFULAT_OFFSET, default_query_params;

  DEFULAT_LIMIT = 20;

  DEFULAT_OFFSET = 0;

  default_query_params = function(req, res, next) {
    var limit, offset, query;
    query = req.query;
    if (query.limit === void 0) {
      query.limit = DEFULAT_LIMIT;
    }
    if (query.offset === void 0) {
      query.offset = DEFULAT_OFFSET;
    }
    limit = parseInt(query.limit);
    offset = parseInt(query.offset);
    limit = (function() {
      switch (false) {
        case limit !== NaN:
          return DEFULAT_LIMIT;
        case !(limit > DEFULAT_LIMIT):
          return DEFULAT_LIMIT;
        case !(limit <= 0):
          return DEFULAT_LIMIT;
        default:
          return limit;
      }
    })();
    offset = (function() {
      switch (false) {
        case offset !== NaN:
          return DEFULAT_OFFSET;
        case !(offset > DEFULAT_OFFSET):
          return DEFULAT_OFFSET;
        case !(offset < 0):
          return DEFULAT_OFFSET;
        default:
          return offset;
      }
    })();
    query.limit = limit;
    query.offset = offset;
    return next();
  };

  module.exports = default_query_params;

}).call(this);
