// Generated by CoffeeScript 1.10.0
(function() {
  'use strict';
  module.exports = function(sequelize, DataTypes) {
    var Task;
    Task = sequelize.define('Task', {
      title: {
        type: DataTypes.STRING,
        validate: {
          notEmpty: true
        }
      },
      desc: DataTypes.STRING,
      done: DataTypes.BOOLEAN,
      createdAt: DataTypes.DATE,
      updatedAt: DataTypes.DATE
    }, {
      tableName: 'tasks',
      classMethods: {
        associate: function(models) {}
      }
    });
    return Task;
  };

}).call(this);
