// Generated by CoffeeScript 1.10.0
(function() {
  'use strict';
  module.exports = function(sequelize, DataTypes) {
    var User;
    User = sequelize.define('User', {
      username: DataTypes.STRING,
      password: DataTypes.STRING,
      createdAt: DataTypes.DATE,
      updatedAt: DataTypes.DATE
    }, {
      classMethods: {
        associate: function(models) {}
      }
    });
    return User;
  };

}).call(this);
